# -*- coding: utf-8 -*-
"""Analise_Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxdgiRxzSd0HYE23uHyc1M_LIg884_wo

### importar a base de dados
### visualizar e tratar a base de dados
### Olhar as informações disponiveis
### Construir analise
### Identificar o motivo dos clientes cancelarem o cartão de crédito
"""

import pandas as pd
tabela = pd.read_csv('/content/drive/MyDrive/minicursocienciasdados/Minicurso Análise de Dados no Python/ClientesBanco.csv', encoding='latin1')
tabela = tabela.drop('CLIENTNUM', axis=1)
display(tabela)

tabela = tabela.dropna()
display(tabela.info())

display(tabela.describe().round(1))

qtde_categoria = tabela['Categoria'].value_counts()
display(qtde_categoria)

qtde_categoria_perc = tabela['Categoria'].value_counts(normalize=True)
display(qtde_categoria_perc)

import plotly.express as px

for coluna in tabela:

  grafico = px.histogram(tabela, x=coluna, color='Categoria')
  grafico.show()

"""# Resultado da análise: Com maior quantidades de produtos contratados o cliente cancela menos o cartão.
# Incentivo e bônus para os clientes usarem mais o cartão
"""

